### ISSUE TITLE
New hardware issue

### ISSUE THREAD

**Issue by owenduffy** [Emile666/stc1000_stm8#10]
Hi, I had problems programming a newer version of the STC-1000. Solution given at https://owenduffy.net/blog/?p=18048 .
I did not try, but it may have been possible to program the original unlabelled chip once C2 was fitted. By the time I had removed the front panel board, I might as well replace the MCU.
You are welcome to use any of the content for this repo or associated wiki.

Owen

2020/07/12: I can add that it was not possible to program the chip on a new unit even after fitting C1 and C2... the unmarked chip may have been an OTP.

**Comment by matsstaff** [comment]
Interesting find! Thanks for sharing!
