### ISSUE TITLE
Enter menu

### ISSUE THREAD

**Issue by adool88** [Emile666/stc1000_stm8#2]
on 103f3 programmed with STVD can't enter menu. S button switches between some temps. S long press leads to Off. Another S long press leads to restart. If I quickly press up I enter menu (Pr1-...Pr5- Set), but S press leads to main screen and so on. Help! :)

**Comment by Emile666** [comment]
I assume you removed the 003f3 device and resoldered an 103f3 device? At least that is what I conclude from your post. Could it be that there a pins soldered together? Or shorted? Did you measure all pins to not connect to each-other?

In other words: make sure that the hardware connections are oke.

**Comment by adool88** [comment]
Hi,

Thanks for response. 
Yes, chip resoldered ( to 103f3). Twice.
Will measure, but at least under microscope it looks ok.
I also soldered 3 pieces of 4.7k resistors (R25, 26, 27 or so) on mainboard. Two of them are not connected to any trace. I have new version board, all mods are done as per your description.

BR,
Darius Stauskas

**Comment by adool88** [comment]
Hi,

Found solder joint on buttons.
Everything works now as expected.
Sorry for false alarm and BIG thanks for software.

BR,
Darius Stauskas

**Comment by Emile666** [comment]
No problem! Glad to hear that it was hardware related!
