### ISSUE TITLE
STC is getting really warm

### ISSUE THREAD

**Issue by tjarmann** [Emile666/stc1000_stm8#6]
I have two STCs with the STM8S003F3, and I upgraded them before testing them. Now, I notice that they are getting a lot warmer than other STCs I have (the one matsstaff fiddled with). I insulated my probe and stuck it in the STC case, and it is measuring~50 C. Is this normal? Are these STCs like this regardless of the firmware? I feel reluctant to enclosing this in a box and having it on for weeks..
The probe is not calibrated, but i can feel the heat coming of the STC.
There is no load on the relays.
I have two probes connected to the STC, and the ambient temperature is (uncalibrated) ~20 C.

Update: Inside the case, close to the little transformer, I now read 72 C. It's been running (still without load on the relays) for four hours.

I am new to github and have no idea how I should contact you, so this is how i chose to do it. I am sorry if it is the wrong way.

**Comment by Emile666** [comment]
Tjarmann,

 

I have never noticed any problems with the power-supply of these devices. However: the power-supply on the board is pretty small and can only deliver a small amount of power. But again: never had a problem with it. Fifty degrees is about normal I would say, it should not get above 80 degrees. It is very well possible that with my firmware the device has to work harder and thus draws a bit more power.

 

I would say that it is good to keep an eye on it, but don't worry too much about it.

 

Regards,

 

Emile van de Logt

**Comment by tjarmann** [comment]
I finally got a hold of a FLIR camera and checked the STC out. The tiny transformer is definitely the culprit, heating up to 140C. I doubt this has to do with your firmware. The label on my STC says 110-220V, but my outlet is 230V. I'm guessing that my device has a transformer that is badly scaled for 230V operations.

Anyway, thank you for your response :)
